services:
  x-kafka-common: &kafka-common
    image: bitnami/kafka:3.7
    environment: &kafka-common-env
      KAFKA_ENABLE_KRAFT: yes
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_KRAFT_CLUSTER_ID: porfolio-application
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: false
    networks:
      - proxynet

  kafka-0:
    <<: *kafka-common
    restart: always
    ports:
      - "9094:9094"
    environment:
      <<: *kafka-common-env
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-0:9092,EXTERNAL://host.docker.internal:9094
    volumes:
      - kafka_0_data:/bitnami/kafka

  kafka-1:
    <<: *kafka-common
    restart: always
    ports:
      - "9095:9095"
    environment:
      <<: *kafka-common-env
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9095
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,EXTERNAL://host.docker.internal:9095
    volumes:
      - kafka_1_data:/bitnami/kafka

  kafka-2:
    <<: *kafka-common
    restart: always
    ports:
      - "9096:9096"
    environment:
      <<: *kafka-common-env
      KAFKA_CFG_NODE_ID: 2
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9096
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,EXTERNAL://host.docker.internal:9096
    volumes:
      - kafka_2_data:/bitnami/kafka

  #  schema-registry:
  #    image: bitnami/schema-registry:7.6
  #    ports:
  #      - '127.0.0.1:8081:8081'
  #    depends_on:
  #      - kafka-0
  #      - kafka-1
  #      - kafka-2
  #    environment:
  #      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
  #      SCHEMA_REGISTRY_KAFKA_BROKERS: PLAINTEXT://kafka-0:9092,PLAINTEXT://kafka-1:9092,PLAINTEXT://kafka-2:9092
  #    networks:
  #      - proxynet

  ui:
    image: provectuslabs/kafka-ui:v0.7.0
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka-0:9092
      KAFKA_CLUSTERS_0_NAME: kraft
    networks:
      - proxynet

  postgres:
    image: debezium/postgres:16
    env_file:
      - .env
    hostname: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: postgres-pw
      POSTGRES_DB: personalization
    #volumes:
    #  - postgres_data:/var/lib/postgresql/data
    #  - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - proxynet

  redis:
    image: redis:7
    hostname: redis
    container_name: redis
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
    ports:
      - "6379:6379"
    networks:
      - proxynet

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis_insight
    hostname: redis_insight
    ports:
      - "5540:5540"
    networks:
      - proxynet
    depends_on:
      - redis

  jobmanager:
    image: flink:2.1.1
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager        
    networks:
      - proxynet

  taskmanager:
    image: flink:2.1.1
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
    networks:
      - proxynet

#  backend:
#    build: ../.
#    container_name: backend
#    depends_on:
#       - kafka-0
#       - postgres
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/personalization
#      SPRING_DATASOURCE_USERNAME: user
#      SPRING_DATASOURCE_PASSWORD: pass
#      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#      TOPIC_EVENTS: events
#      TOPIC_PROFILES: profiles
#    ports:
#      - "9090:8080"
#    networks:
#      - proxynet

#  kafka-connect:
#    build:
#      context: confluent-hub-components/infra/kafka-connect
#    ports:
#      - "8083:8083"
#      - "9875:9875"
#      - "9876:9876"
#    depends_on:
#      - kafka-0
#      - kafka-1
#      - kafka-2
#      - schema-registry
#      - postgres
#    environment:
#      CONNECT_BOOTSTRAP_SERVERS: kafka-0:9092
#      CONNECT_REST_PORT: 8083
#      CONNECT_GROUP_ID: 'kafka-connect'
#
#      CONNECT_REST_ADVERTISED_HOST_NAME: 'localhost'
#
#      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
#      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
#      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1

#      CONNECT_CONFIG_STORAGE_TOPIC: 'connect-config-storage'
#      CONNECT_OFFSET_STORAGE_TOPIC: 'connect-offset-storage'
#      CONNECT_STATUS_STORAGE_TOPIC: 'connect-status-storage'

#      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
#      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
#      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
#      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"

#      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081/'

#      CONNECT_PLUGIN_PATH: /usr/share/java,/etc/kafka-connect/jars
#    volumes:
#      - ./confluent-hub-components/:/etc/kafka-connect/jars
#    networks:
#      - proxynet

networks:
  proxynet:
    name: custom_network

volumes:
  kafka_0_data:
  kafka_1_data:
  kafka_2_data:
