
server:
  port: 9090

spring:
  kafka:
    bootstrap-servers: localhost:9094

    producer:
      # Включает транзакции (обязательно для EOS)
      transaction-id-prefix: ingestion-tx-

      # Идемпотентность (Kafka гарантирует EOS)
      properties:
        enable.idempotence: true
        acks: all
        retries: 10

      # Сериализаторы
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    template:
      default-topic: raw-user-events