server:
  port: 9090

spring:
  kafka:
    bootstrap-servers: localhost:9094,localhost:9095,localhost:9096

    producer:
      transaction-id-prefix: ingestion-tx-

      properties:
        enable.idempotence: true
        acks: all
        retries: 10

    template:
      default-topic: raw-user-events
