
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/personalization
    username: postgres-user
    password: postgres-pw
    database: personalization
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000
  slq:
    init:
      mode: never  
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
       


topics:
  events: events
  profiles: profiles

logging:
  level:
    root: INFO