
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/personalization
    username: user
    password: pass

topics:
  events: events
  profiles: profiles

logging:
  level:
    root: INFO